#:import Window kivy.core.window.Window
#:import dp kivy.metrics.dp

<HighlighterDialog>:
    title: 'HighlighterDialog'
    background_color: .6, .6, .8, .9
    overlay_color: 0, 0, 0, 0
    size_hint: [None, None]
    size: min(Window.size[0], dp(500)), min(Window.size[1], dp(150))
    MDTextField:
        id: text_input
        on_text_validate: root.validate(self.text)
        multiline: False
