FROM dorowu/ubuntu-desktop-lxde-vnc
MAINTAINER admin@lnorb.com
env TERM=xterm
RUN adduser --disabled-password --gecos '' ubuntu
RUN adduser ubuntu sudo
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER ubuntu
WORKDIR /home/ubuntu
RUN curl https://install.lnorb.com | bash
USER root
WORKDIR /
