name: test linux
on:
  push:
    branches: [ build_linux ]
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.S3_KEY }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}
    PYARMOR: ${{ secrets.PYARMOR }}
jobs:
  build_linux:
    runs-on: ubuntu-20.04
    env:
      os-name: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: Install requirements
        run: |
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Run tests
        run: python ./build.py test.test
      - name: Build for Linux
        run: python ./build.py armor.build-linux
      - name: Upload requirements.txt
        uses: actions/upload-artifact@v2
        with:
          name: requirements.txt
          path: requirements.txt
