# name: tests
# on:
#   push:
#     branches: [ dev, main ]
# jobs:
#   test_linux:
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-python@v2
#         with:
#           python-version: '3.9'
#           cache: 'pip'
#       - run: pip install -r requirements.txt -r requirements-dev.txt
#       - run: pytest tests/
